# Generated by Django 3.0.5 on 2020-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UTM_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_url', models.CharField(max_length=25, verbose_name='Website URL')),
                ('utm_source', models.CharField(blank=True, max_length=25, verbose_name='Campaign Source')),
                ('utm_medium', models.CharField(blank=True, max_length=25, verbose_name='Campaign Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=25, verbose_name='Campaign Name')),
                ('utm_term', models.CharField(blank=True, max_length=25, verbose_name='Campaign Term')),
                ('utm_content', models.CharField(blank=True, max_length=25, verbose_name='Campaign Content')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['created_on'],
            },
        ),
    ]
