# Generated by Django 4.0.5 on 2022-07-01 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=254, verbose_name="Website URL")),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Campaign Source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Campaign Medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Campaign Name"
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Campaign Term"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Campaign Content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
